### ISSUE TITLE
Databazovy diagram

### ISSUE THREAD

**Issue by AdamH4** [AdamH4/Webte2-project#10]
- pridat do README.md

**Comment by kobe-ra** [comment]
[link](https://dbdiagram.io/d/600adad380d742080a37784d)
pw: eheheh

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/115121402-d9159f00-9fb2-11eb-9378-dc53b0db77fd.png)

**Comment by kobe-ra** [comment]
zostava otvorene pre moznost buducej upravy

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/115966408-b55fd500-a52d-11eb-95f8-6eb169020083.png)

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/115966622-ceb55100-a52e-11eb-906f-47ff4028551f.png)

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/115966673-fdcbc280-a52e-11eb-870e-da4b1e708c95.png)

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/115966917-096bb900-a530-11eb-99bd-d6bb818e415f.png)

**Comment by AdamH4** [comment]
Inak zacinam rozmyslat ako chceme ukladat parovacie otazky, lebo pozeram sa na ten graf a nebude to mozne kedze na odpoved mame len stlpec **asnwer** v tabulke **Answers**.

**Comment by CavojovaEmma** [comment]
Ak ratame s tym ze video je smerodajne tak staci parovanie otazok s odpovedami 1:1 a potom by to malo byt v pohode

**Comment by kobe-ra** [comment]
bavili sme sa ze ulozime json

**Comment by AdamH4** [comment]
Fu no vobec si nepamatam JSON, ale budete to robit vy, tak hlavne nech tomu vy rozumiete 😄

**Comment by CavojovaEmma** [comment]
Vsimla som si ze v tabulke **questions** chyba stlpec pre obsah otazky, @kobe-ra doplnis ho tam?

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/116566719-46a4c200-a907-11eb-84a3-2f75e117319b.png)

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/116780937-ed13d300-aa7f-11eb-95f9-477bd8e7530f.png)
este som to prehodnotil, question by mal byt text, nie string.

**Comment by kobe-ra** [comment]
![image](https://user-images.githubusercontent.com/32091524/117149598-a5f74c00-adb7-11eb-9434-f9691ca0be1e.png)
